### ISSUE TITLE
unable to Send command to ip2SL

### ISSUE THREAD

**Issue by mgkooi** [plarsson/com.globalcache#8]
Hi I'm trying to figure out how to send a command to my Marantz receiver by IP2SL.

**When I use the iTest application it works with these settings:**
ip: 192.168.1.31
Serial 1 (4999)
Command: @PWR:1

**Settings from the IP2SL gui/ Serial Parameters**
Multiple Ports:	Enabled
Baud Rate: 9600
Flow Control: None
Stop Bits: 1
Parity: None
Data Bits: 8

this is the configuration in Homey. It doesn't matter which command I send, all I get is a "CLIENT IS NOT DEFINED" message.
My gues is that the app is connecting to port 4998. Please help,

{
  "ir": {
    "devices": []
  },
  "serial": {
    "baudrate": "9600",
    "flowcontrol": "None",
    "parity": "None",
    "cmds": [
      {
        "name": "PowerOn",
        "value": "\\uPWR:1\\u000D"
      }
    ]
  }
}

**Comment by mgkooi** [comment]
BTW I'm using homeyVersion | "5.0.0-rc.50"

**Comment by mgkooi** [comment]
I think I found the issue, the app is written for V2 en not V5. I pulled the repository to run it in dev. mode and see these errors:
The app has to be rewritten to V5 :( 

2021-01-14 10:04:21 [err] [ManagerDrivers] [flexethernet] Error: Please replace `new FlowCard()` with `this.homey.flow.getCard()`
    at new FlowCard (/opt/homey-client/node_modules/homey-apps-sdk-v3/lib/FlowCard.js:25:13)
    at new FlowCardAction (/opt/homey-client/node_modules/homey-apps-sdk-v3/lib/FlowCardAction.js:16:5)
    at iTachFlexEthernetDriver.onInit (/drivers/ip2ir/driver.js:9:26)
    at /opt/homey-client/node_modules/homey-apps-sdk-v3/lib/Driver.js:62:18
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by plarsson** [comment]
see https://github.com/plarsson/com.globalcache/issues/9
